### ISSUE TITLE
Force override dependencies

### ISSUE THREAD

**Issue by ZotyDev** [juraj-hrivnak/Pakku#12]
There are some mods that depend on others, and when you do `pakku add <slug>` it will add the depencies too, thing is, sometimes the mod you are adding has an dependency on an old or deprecated mod that got updated, my example `dramatic-trees` is the new `dynamic-trees` for `1.12.2` (fork) and when I add the addons for it, lets say Quark Dynamic Trees, it adds `dynamic-trees` as a dependency and installs it.

Currently, I need to manually change the dependency ID and remove the wrongly added project, but running `pakku upade --all` will revert the changes.

Please make a way to prevent the manual changes to roll back, or better yet, provide a `pakku add <slug> --override_dependency <old dependency slug>:<new dependency slug>`.

Thanks for your work! Pakku is a great tool :D

**Comment by juraj-hrivnak** [comment]
Hello,
I am thinking of `—no-deps` flag. Overriding a dependency seems too verbose.

**Comment by juraj-hrivnak** [comment]
It would also be nice to show dependencies of the project before adding it, and be able to turn individual off somehow.

**Comment by juraj-hrivnak** [comment]
`--no-deps` flag added in v0.9.0
