### ISSUE TITLE
Ability to specify version when adding project

### ISSUE THREAD

**Issue by GAsplund** [juraj-hrivnak/Pakku#21]
Our pack uses mods that are incompatible in newer versions, which means that we need to lock it to a set version. Adding a way for specifying the version (or file name) would be very helpful for us.

Reading the documentation it might be possible to do using the `projects` property, but I was not able to make it work.

**Comment by juraj-hrivnak** [comment]
That is already possible: https://juraj-hrivnak.github.io/Pakku/managing-projects.html#adding-projects

> The `<projects>...` argument accepts only the project slug or ID; plus optionally specified file ID (using `:` as separator) and allows multiple projects to be added.

Run: `pakku add <projectId>:<fileId>`and then `pakku set <projectId> -u none` to set the update strategy to `none`. (That will stop it from updating.)

**Comment by GAsplund** [comment]
Oh, I am blind. That worked, thanks for the guidance!

**Comment by juraj-hrivnak** [comment]
You're welcome
