### ISSUE TITLE
Configurable subpath for projects

### ISSUE THREAD

**Issue by SettingDust** [juraj-hrivnak/Pakku#27]
Like https://packwiz.infra.link/reference/additional-options/
I'm placing many mods into sub dir of `mods`

https://modrinth.com/mod/mod-sets

**Comment by juraj-hrivnak** [comment]
How so? Do you want to set up a custom subpath for each project or all projects?

**Comment by SettingDust** [comment]
> How so? Do you want to set up a custom subpath for each project or all projects?

Specify the path when adding the project. If not, add it to the default path.

**Comment by juraj-hrivnak** [comment]
Please provide some examples. I do not understand.

**Comment by SettingDust** [comment]
> Please provide some examples. I do not understand.

For example. I'll add sodium and sodium extras to `./mods/optimize.client`. iris to `./mods/decoration.client`

**Comment by juraj-hrivnak** [comment]
Okay, thanks. So, it's a subpath from the default directory.

**Comment by SettingDust** [comment]
I'm going to implement this feature. How will you implement it?
There are some options in my mind.
1. A flag like packwiz `--meta-folder <path>`. Specify the relative path fully that will ignore the project type, such as `mods/optimization`.
2. A flag that specify relative path based on the project type.

**Comment by juraj-hrivnak** [comment]
I appreciate that, but I already started implementing it. You can look at the other issues if you want to contribute. :P

Pakku's design primarily uses the [config file](https://juraj-hrivnak.github.io/Pakku/config-file.html) to override properties of projects or set various options for them. 
So, there will be a new `subpath` property that you will be able to set using the config file.

Example:
```json
{
  "projects": {
    "sodium-extras": {
      "subpath": "optimize.client"
    },
    "iris": {
      "subpath": "decoration.client"
    }
  }
}
```

Changing the default directory for the project types will be possible using a global variable:

```json
{
  "mods_dir": "<path>",
  "datapacks_dir": "<path>"
}
```

Also, I will implement support for project overrides.
