### ISSUE TITLE
Project aliases 

### ISSUE THREAD

**Issue by SettingDust** [juraj-hrivnak/Pakku#33]
A config like https://sinytra.org/docs/connector/configuration#global-mod-aliases and https://fabricmc.net/wiki/documentation:fabric_mod_json#mod_loading `provides` is useful.

`--no-deps` isn't enough in this situation. A project is able to provide another project in Minecraft world

**Comment by SettingDust** [comment]
I'm going to add `provide` to project model

**Comment by juraj-hrivnak** [comment]
Why not like this:

```json
"projects": {
  "forgified-fabric-api": {
    "alias": "fabric-api",
    "aliases": ["fabric-api", "foo", "bar"]
  }
}
```

I think this would be better.
