### ISSUE TITLE
`sync` command

### ISSUE THREAD

**Issue by Xikaro** [juraj-hrivnak/Pakku#56]
Is there a planned function, something like the "refresh" command? When the folder mods already contains mod changes, i.e. updated manually or via the launcher, and pakku updated them in pakku-lock.json, based on the file name and version, if the version has changed
![Screenshot_162](https://github.com/user-attachments/assets/bee51eb9-a6da-4129-95e9-a13562b3b8c2)

**Comment by juraj-hrivnak** [comment]
The sync command could detect the project files files in your modpack add ask you whether you want to update, add (or remove?) projects from the lock file.

Also a watch command could be useful to detect these things add sync automatically, but also hard to implement properly.

Under the hood, there are already  functions in the Pakku API to do that. You can use a sha1 hash for Modrinth and a Murmur2 hast for CurseForge, to get a project.
