### ISSUE TITLE
mod not found on github

### ISSUE THREAD

**Issue by xronin01** [juraj-hrivnak/Pakku#65]
![Screenshot_20241118-111755_Termux](https://github.com/user-attachments/assets/7911eb2e-c90a-42e5-a80d-1601bf65cd80)
https://github.com/GTNewHorizons/TinkersConstruct

**Comment by juraj-hrivnak** [comment]
What version of Pakku do you have?

**Comment by xronin01** [comment]
0.21.0

**Comment by juraj-hrivnak** [comment]
Try using the debug flag

**Comment by xronin01** [comment]
![Screenshot_20241118-113250_Termux](https://github.com/user-attachments/assets/9eceafce-0fe0-4fb0-89bb-39bc995f0bff)

**Comment by juraj-hrivnak** [comment]
Hmm, 403 Forbidden.
Something is blocking your connection.
