### ISSUE TITLE
 MOD {x} is already added output shouldn't be threadted as an error

### ISSUE THREAD

**Issue by TheBossMagnus** [juraj-hrivnak/Pakku#67]
Right now is red:
![image](https://github.com/user-attachments/assets/8f005108-25da-4a19-bdee-6bf81a3fb4f6)

in my opinion should be blue like:
![image](https://github.com/user-attachments/assets/ed0f12b6-1ebc-40b2-9e53-481c935af9c1)
or at worst yellow like:
![image](https://github.com/user-attachments/assets/adab90e5-19ac-461a-a663-ce4ce93c3a17)

Obviously, this is opinionated, but when a user adds a project, the status of the pack remains the same whether the project already exists or is added successfully. Nothing has really gone wrong.
For this reason, I suggest the change. However, instead of pring it, I would prefer to get an opinion from the developer or anyone else...

**Comment by juraj-hrivnak** [comment]
Thanks for the suggestion.
Creating color guidelines for various scenarios like this might be a good idea.

When I designed it, the blue color indicated dependency management; green indicated success, red indicated error, and yellow indicated warning.

Technically it made sense that this is an error, but it could also be a warning or just a plain message.

**Comment by TheBossMagnus** [comment]
Are there any other colors available?

**Comment by juraj-hrivnak** [comment]
Basically these:

![](https://raw.githubusercontent.com/fidian/ansi/master/images/color-codes.png)

**Comment by SettingDust** [comment]
Another line should be appended, like "Trying to replace the existed one". The level should be warning or info here.

**Comment by juraj-hrivnak** [comment]
Fixed in 0.23.0
